apiVersion: v1
kind: ConfigMap
metadata:
  name: settleflow-config
  namespace: settleflow
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/settleflow"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
  CORS_ALLOWED_ORIGIN: "http://localhost:3000"
  PSP_ALPHA_URL: "http://psp-mocks-service:8081/v1/payments"
  PSP_BETA_URL: "http://psp-mocks-service:8082/v1/charges"
  PSP_GAMMA_URL: "http://psp-mocks-service:8083/v2/settle"
  NEXT_PUBLIC_BACKEND_URL: "http://localhost:8080"
  BACKEND_URL: "http://backend-service:8080"
---
apiVersion: v1
kind: Secret
metadata:
  name: settleflow-secrets
  namespace: settleflow
type: Opaque
stringData:
  POSTGRES_PASSWORD: "password123"
  SPRING_DATASOURCE_PASSWORD: "password123"
