apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: settleflow

resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - psp-mocks.yaml
  - backend.yaml
  - frontend.yaml
  - reconciliation-cronjob.yaml
  - ingress.yaml
  - public-tunnel.yaml

